// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vduubpniwiyuqdvinsqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdXVicG5pd2l5dXFkdmluc3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NTUxMjAsImV4cCI6MjA4NDIzMTEyMH0.zfTR1x3UJ8NzS2TITZX9rMG6aIn_RS7T_GYSwegxKQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});